# Generated by Django 5.2.9 on 2026-02-01 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_classroom_subjects_classroom_teacher'),
        ('users', '0002_profile_classroom_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school.classroom'),
        ),
    ]
