# Generated by Django 5.2.9 on 2026-02-06 01:19

import django.core.validators
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_classroom_options_alter_subject_options_and_more'),
        ('users', '0003_alter_profile_classroom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username']},
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), users.models.validate_avatar_size]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('teacher', 'Teacher'), ('student', 'Student')], db_index=True, default='student', max_length=20),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role', 'is_active'], name='users_profi_role_ee642a_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['classroom'], name='users_profi_classro_a5b00e_idx'),
        ),
    ]
