# Generated by Django 5.2.9 on 2026-02-06 01:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
        ('school', '0003_alter_classroom_options_alter_subject_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grade',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(limit_choices_to={'profile__role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school.subject'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Grade cannot be negative'), django.core.validators.MaxValueValidator(100, message='Grade cannot exceed 100')]),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'subject'], name='grades_grad_student_a52746_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['subject', 'created_at'], name='grades_grad_subject_19fbbc_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'is_active'], name='grades_grad_student_b66611_idx'),
        ),
    ]
